version: "3.1"
services:
  d-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: my-mysql
    volumes:
      # 永続化用のマウント先
      - ./sql/data:/var/lib/mysql
      # 初期データ
      - ./sql/dump/:/docker-entrypoint-initdb.d
      # my.cnf
      - ./sql/myconf/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
